/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marshal_helloubuntuapp_NativeUtils */

#ifndef _Included_marshal_helloubuntuapp_NativeUtils
#define _Included_marshal_helloubuntuapp_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     marshal_helloubuntuapp_NativeUtils
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_marshal_helloubuntuapp_NativeUtils_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
